### ISSUE TITLE
undefined method `mattr_accessor' for Kredis::Connections:Module upon require

### ISSUE THREAD

**Issue by mensfeld** [rails/kredis#1]
Hey,

My name is Maciej Mensfeld and I run a research security project called https://diffend.io.

While that's not a security issue, wanted to bring to your attention, that upon requiring the `kredis` (diffend does that to run a sandbox for security assessment of gems based on their behaviors), it fails with:

```
undefined method `mattr_accessor' for Kredis::Connections:Module
```

which (probably) indicates, that `activesupport` is not present upon the first usage if `mattr_accessor`.

ref https://github.com/rails/kredis/blob/main/lib/kredis/connections.rb#L4

repro:

Gemfile
```ruby
source 'https://rubygems.org'

gem 'kredis'
```

steps:

1. `bundle install`
2. `bundle exec irb`
3. `bundle exec ruby -e 'require "kredis"'`

**Comment by kaspth** [comment]
Fixed on main, thanks! We'll prep another release later.

**Comment by mensfeld** [comment]
@kaspth FYI 0.2.1 still has this issue.

**Comment by kaspth** [comment]
Ah, we're running Kredis in production for our Rails app and not seeing it. But I can see your reproduction steps above, so let me fix it for that too, thank you!

**Comment by mensfeld** [comment]
Thanks :) the reason why you do not see this, is that you have it in the Rails setup that is loaded, while the gem itself does not require things that are needed by it in isolation. Common thing. Thanks once again.

**Comment by kaspth** [comment]
Yes, totally. I've fixed it for good here: https://github.com/rails/kredis/commit/cd69ef0989a9959ec9ec5347b9649e19c1ae9885

Thanks for checking back again, sorry we didn't catch it with the first fix! 🙌

**Comment by mensfeld** [comment]
@kaspth thank you for fixing it.

> Thanks for checking back again

I don't ;) the system does ;)

**Comment by kaspth** [comment]
Nice, it sounds good 👍
