### ISSUE TITLE
kredis_integer with expires_in

### ISSUE THREAD

**Issue by valenciaj** [rails/kredis#103]
Hi there!

I have the following code:
```ruby
class Box < ActiveRecord::Base
  kredis_integer :locked_by_user_id, expires_in: 1.minute
end
```

But when I set `locked_by_user_id` to any value never expires:
```ruby
b = Box.where(id: 10000).first
b.locked_by_user_id = Current.user.id
```
Redis' monitor output:
```
1666101562.986655 [0 xxx.xxx.xxx.xxx:xxxx] "set" "boxes:10000:locked_by_user_id" "10000"
```

Kredis isn't setting expires `ex` param.

What's wrong with my code?

**Comment by bdewater** [comment]
Can't repro, getting a NoMethodError for `locked_by_user_id=` on my model. 

But `b.locked_by_user_id` should return a `Kredis::Types::Integer` instance, so try `b.locked_by_user_id.value = Current.user.id`.
