### ISSUE TITLE
Bolding log text with positional boolean to be deprecated in Rails 7.2

### ISSUE THREAD

**Issue by connordoner** [rails/kredis#108]
When I run `rails test` in an app running the edge version of Rails, I receive the following warning:

> DEPRECATION WARNING: Bolding log text with a positional boolean is deprecated and will be removed in Rails 7.2. Use an option hash instead (eg. `color("my text", :red, bold: true)`). (called from formatted_in at /usr/local/lib/ruby/gems/3.2.0/gems/kredis-1.3.0.1/lib/kredis/log_subscriber.rb:18)

This stems from the use of the `color` function in `log_subscriber.rb`:

https://github.com/rails/kredis/blob/6297ad5d52ebab795b76b5ba279d1aae2b0a4637/lib/kredis/log_subscriber.rb#L18

I appreciate that this won't be an issue for most people yet but it feels better to report it now and get ahead of the curve.

**Comment by dmcge** [comment]
This is fixed in https://github.com/rails/kredis/pull/98. It just hasn’t been released yet.

**Comment by connordoner** [comment]
Crikey — not sure how I missed that! Sorry.

That said, thanks for the PR. Fingers crossed that it gets released soon.

Do we know of any way to suppress the warning in the meantime?
