### ISSUE TITLE
undefined method `compact_blank' for [0, -1]:Array

### ISSUE THREAD

**Issue by scottbarrow** [rails/kredis#13]
Using a typed hash, and when reading `elements`

 undefined method `compact_blank' for [0, -1]:Array
Did you mean?  compact
from /Users/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/kredis-0.2.1/lib/kredis/types/proxy.rb:22:in `log_message'

**Comment by scottbarrow** [comment]
Can you confirm if `kredis_unique_list` supports JSON types?

**Comment by dhh** [comment]
Hadn't tried, actually. If it doesn't, feel free to have a look at making it so ✌️

**Comment by kaspth** [comment]
> undefined method `compact_blank' for [0, -1]:Array Did you mean? compact from /Users/scott/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/kredis-0.2.1/lib/kredis/types/proxy.rb:22:in `log_message'

That should be fixed in 0.2.2.
