### ISSUE TITLE
v1.6.0 no longer works with Redis cluster

### ISSUE THREAD

**Issue by pbstriker38** [rails/kredis#131]
Attempting to use defaults raises an error because the `unwatch` command is not supported on Redis clusters.

```ruby
Loading development environment (Rails 7.0.8)
irb(main):001> last_seen_at = Kredis.datetime('last_seen_at', default: 20.minutes.ago, expires_in: 1.week)
[2023-10-31T16:28:21.283-07:00] INFO:   Kredis  (43.7ms)  Connected to shared
[2023-10-31T16:28:21.289-07:00] DEBUG:   Kredis Proxy (1.6ms)  EXISTS? last_seen_at  
[2023-10-31T16:28:21.291-07:00] DEBUG:   Kredis Proxy (1.6ms)  SET last_seen_at ["2023-10-31T23:08:21.239912000Z"] {:ex=>1 week}
/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/redis-4.8.1/lib/redis/cluster.rb:152:in `send_command': Cluster client doesn't know which node the unwatch command should be sent to. (Redis::Cluster::AmbiguousNodeError)
/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/redis-4.8.1/lib/redis/cluster.rb:152:in `send_command': Cluster client doesn't know which node the unwatch command should be sent to. (Redis::Cluster::AmbiguousNodeError)
```

https://github.com/redis/redis-rb/blob/v4.8.1/lib/redis/cluster.rb#L151

**Comment by dhh** [comment]
cc @lewispb

**Comment by lewispb** [comment]
I just ran the test suite against Redis Cluster locally and most of it failed. Looks like we don't support Redis Cluster.

It's not just `unwatch` that's unsupported, `multi` and `mget` are too, both of which are used by Kredis.

We could add a note to the Readme perhaps? https://github.com/rails/kredis/pull/137

**Comment by KJTsanaktsidis** [comment]
> It's not just unwatch that's unsupported, multi and mget are too, both of which are used by Kredis.

FWIW I'm in the process of trying to get as much of `watch`/`multi` as makes sense working with the Ruby redis cluster driver: https://github.com/redis-rb/redis-cluster-client/issues/299

Once we get that support landed, making kredis work with redis-cluster should be a case of figuring out which keys need to be accessed transactionally together, and adding `{hashtags}` to them so that they hash to the same slot
