### ISSUE TITLE
Is the behavior correct when a model is destroyed?

### ISSUE THREAD

**Issue by nzwsch** [rails/kredis#134]
I am not familiar with the behavior of Redis, so maybe it is not a problem in the way Redis works.
I was wondering about the part where the keys are not deleted from Redis when a model using Kredis values is destroyed.

Here is a demo:

```ruby
class Person < ApplicationRecord
  kredis_string :name
end
```

```ruby
>> r = Redis.new
=> #<Redis client v4.8.1 for redis://127.0.0.1:6379/0>
>> r.keys
=> []
>> person = Person.create
=> #<Person:0x00007f1f64a9a9e0 ...
>> person.name.value = "nzwsch"
  Kredis  (1.1ms)  Connected to shared
  Kredis Proxy (0.9ms)  SET people:5:name ["nzwsch"] 
=> "nzwsch"
>> person.destroy
=> #<Person:0x00007f1f64a9a9e0 ...
>> r.get("people:5:name")
=> "nzwsch"
```

Normally the person model is deleted from the database after the destroy is called, but from the Redis client it is not deleted and the value can be referenced directly by key.

I can manually add an after_destroy callback to the Rails model, but am I wrong to expect this to be the default behavior on the Kredis side?
If this library can support this, please comment on your support policy and I will gladly prepare a PR.

**Comment by dhh** [comment]
Support would have to be conditional, because right now, Kredis doesn't know anything about Active Record, only Active Model. But I do see the point here. It should probably be explicit, though. Like `kredis_string :name, dependent: :delete` or something like that, matching what we have in Active Record for associations.

**Comment by nzwsch** [comment]
Thank you for your comment.

I am currently using Kredis for a project, but I had almost forgotten the reason for this Issue.
I do think it is clear to set an explicit option.
I don't have to implement new options like `dependent` since `after_change` is supported as an option for Kredis methods.
It would be nice to support a convenient syntax sugar like ActiveRecord, but unfortunately I don't have the passion right now to work on this Issue as a PR.
