### ISSUE TITLE
Kredis but... without Redis?

### ISSUE THREAD

**Issue by phillipspc** [rails/kredis#155]
It seems to me that part of the goal with Rails 8 is to allow full-fledged web apps with fewer external dependencies, one of which is Redis. I have no idea of the technical feasibility of this, but I'd love to continue to be able to use Kredis with my SQLite-all-the-things apps, for example. Is there a world in which this library could work alongside something like [solid_cache](https://github.com/rails/solid_cache), perhaps through some sort of adapter approach?

**Comment by jeremy** [comment]
Not directly, since Kredis wraps Redis data types without implementing them itself. You'd need a SQLite extension to reimplement. Essentially a new project.
