### ISSUE TITLE
Is it possible to add ActiveRecord-like change callbacks?

### ISSUE THREAD

**Issue by julianrubisch** [rails/kredis#17]
*Disclaimer: I'm not a Redis expert, at all.*

My naive line of thought was that change callbacks could be used in a variety of scenarios:

- issuing notifications, e.g. when a user is added to a unique list holding "presence"
- updating a view via turbo streams or CableReady, think "live dashboards"
- building chat bots
- ...

**Comment by kaspth** [comment]
Hey, yes, there's something interesting here! Right now this gets close to speculative territory though, so let's get a little more real by seeing some use cases from your app. Is there a place where you're trying to add Kredis that you could reasonably share (with renames/modifications)? That way we can extract rather than invent, which is easier 😄

**Comment by julianrubisch** [comment]
Very speculative indeed, because right now I'm only building this in my head - as kredis itself is quite young. I'm going to build a presence module in one of my apps soon-ish though, so I'll report back with a gist when I'm ready 👍

**Comment by kaspth** [comment]
Perfect that sounds great! I'll close this for now, but once you have more we can just re-open, or start a new one, all good 😄

**Comment by leastbad** [comment]
Redis (and the `redis`) gem make it relatively easy to "subscribe" to updates on a key:

https://github.com/redis/redis-rb/blob/master/examples/pubsub.rb

I think you/we get further, faster, if you think of this potential functionality as being less like an AR callback and more like an ActionCable channel.

Right now, if I was 1. working with a Kredis object eg. `Kredis.string "mystring"` I would likely just take the example linked above and use the Redis gem directly to subscribe and respond to updates.

Conversely, if your goal is to 2. get the AR methods like `kredis_list` to trigger AR callbacks on their models, well, that's interesting. You could likely prototype this as a concern and whip up an example pretty quickly, Julian.

(If there's a third path implied, I apologize for not spotting it!)

**Comment by julianrubisch** [comment]
I managed to play around with this a bit more, and it sent me right down a rabbit hole of ThreadPools etc., looking at the ActionCable pubsub implementation - stuff I'm not really too comfortable with.

Also, since kredis is supposed to be a lightweight adapter for redis data types, a complete pubsub solution doesn't appear to have a place here.

What could bring some flexibility though, is the ability to pass a callback block to mutating operations like `Set#add` etc.

A very naive solution which has no concept of thread safety etc. could look like this:

```rb
class Kredis::Types::Set
  # ...
  def add(*members)
    sadd types_to_strings(members) if members.flatten.any?

    yield members if block_given?
  end
  # ...
end
```

Doing that I was able to write a simple presence module that streams a `CableReady` operation to display a list of users currently viewing a resource:

```rb
resource.present_users.add(current_user.id) do |members|
  StreamPresenceJob.perform_later(members)
end
```

From here it's not a wide stretch to assume that a `Proc` could be placed on the model itself, or a wrapper function defined inside a concern for adding/removing ids to/from the set that allows for this operation.

For reference, here's a short clip:

https://user-images.githubusercontent.com/4352208/120341577-46795700-c2f7-11eb-86a8-234d260adfae.mp4

**Comment by leastbad** [comment]
Are you using a fork of Kredis with block support to do that, @julianrubisch? A link to the implementation (or "an" implementation") would help.

I agree that there's a difference between yielding to a block (which I am very 👍 about) and actually registering pub/sub stuff. That feels like another gem.

On the topic of thread safety, I wonder if Kredis would benefit from the `Thread::Local` mechanism we use in CableReady?
