### ISSUE TITLE
Is there a way to use redis connection pools?

### ISSUE THREAD

**Issue by directionless** [rails/kredis#27]
I love the simplicity of using `kredis` in my models. Is there a way to configure the underlying redis connection to use pools?

**Comment by lxbrito** [comment]
Short answer: No.

However at **your own risk** you can monkeypatch Kredis::Connection to use Mperham ConnectionPool::Wrapper (Multi won't work properly). You can pass pool size in the config.
# module Kredis::Connections
#   def configured_for(name)
#     connections[name] ||= begin
#       logger&.info "[Kredis] Connected to #{name}"
#       configs = configurator.config_for("redis/#{name}")
#       ConnectionPool::Wrapper.new(configs) { Redis.new(configs) }
#     end
#   end
# end

**Comment by directionless** [comment]
Bummer. I hope it's on the docket for future work. I'd love to share the existing connection pools my app is already using.

**Comment by rickychilcott** [comment]
FYI #46 should be referenced here and might be the more appropriate answer for those who come across this in the future...
