### ISSUE TITLE
Redis Hash support

### ISSUE THREAD

**Issue by maboelnour** [rails/kredis#28]
Is there any plan to support `Redis Hash` datatype? if not already in-progress I can PR it.
`Hash` datatype is more memory-efficient to store small JSON data than an ordinary plain key-value.
Check [this](https://redis.io/topics/memory-optimization) section: `Using hashes to abstract a very memory efficient plain key-value store on top of Redis`

**Comment by julianrubisch** [comment]
I'd love to have that!

**Comment by maboelnour** [comment]
@kaspth @dhh

**Comment by julianrubisch** [comment]
started an implementation here: #37
