### ISSUE TITLE
Using advanced ssl_params with Redis connections

### ISSUE THREAD

**Issue by mjc-gh** [rails/kredis#30]
Hi all! Just curious on what's the advice for handling custom `ssl_params` to the Redis connection?

I am using RedisLabs and have self-signed certificates and CA files from them. With that I basically do something like the below when initializing redis connections (for Sidekiq and Rails' cache redis store):

```ruby
cert_store = OpenSSL::X509::Store.new
cert_store.add_file(Rails.root.join('config', 'redislabs_ca.pem').to_s)

ssl_params = {
  cert_store: cert_store,
  cert: OpenSSL::X509::Certificate.new(File.read(
    Rails.root.join('config', 'redislabs_user.crt')
  )),

  key: OpenSSL::PKey::RSA.new(
    Rails.application.credentials.redis[:client_key]
  ),

  verify_mode: OpenSSL::SSL::VERIFY_PEER }
}

redis = Redis.new(url: ENV['REDIS_URL'], ssl_params: ssl_params)
```

I suspect there isn't really a great way to pass all this configuration via yaml. Happy to open a PR which exposes more configuration options but would love some guidance on what I should look to refactor and extend? Maybe `Kredis::Connections` could have a user-extendable hash that maps the supplied `name` to `configured_for` to an optional proc. This proc could receive the results of `configurator.config_for("redis/#{name}")` and let the user update the hash with more options.

My current "solution" is super hacky and it just preemptively populates the `connections` hash in an initializer:

```ruby
 Kredis::Connections.connections[:shared] = Redis.new(
  url: ENV['REDIS_URL'], ssl_params: ssl_params
)
```

Great stuff as always though! This gem is super helpful to some new stuff we're working on.

**Comment by dhh** [comment]
I think your "hacky" solution is the right one. We should just document that this is how to do it.

**Comment by mjc-gh** [comment]
Sounds good! I can submit a PR with some README.md updates.

**Comment by mjc-gh** [comment]
Forgot to close this with #31
