### ISSUE TITLE
Proposal: Provide a `fetch` method similar to `Rails.cache.fetch`

### ISSUE THREAD

**Issue by julianrubisch** [rails/kredis#38]
From the [docs](https://guides.rubyonrails.org/caching_with_rails.html#low-level-caching):

> When passed only a single argument, the key is fetched and value from the cache is returned. If a block is passed, that block will be executed in the event of a cache miss. The return value of the block will be written to the cache under the given cache key, and that return value will be returned. In case of cache hit, the cached value will be returned without executing the block.

I think having this functionality (for scalars, as well as maybe the upcoming Hash implementation) would be neat.

WDYT?

**Comment by dhh** [comment]
Hmm, I haven't hit that in my use of Kredis. Remember we can always access the underlying redis instance as well. I totally get that this might have a use, but I'd prefer to wait and see if it pops up in reality to warrant this. Kredis is primarily about exposing higher-level data structures of Redis, less all of redis or redis-as-a-cache.

**Comment by julianrubisch** [comment]
Yep, was just a thought about DX that cropped up in _my_ experience of using it.
