### ISSUE TITLE
Kredis attributes causing "no _dump_data is defined" error when writing to Rails.cache

### ISSUE THREAD

**Issue by brenogazzola** [rails/kredis#40]
EDIT: The initial bug report was incorrect. It implied the problem was `kredis_hash` and the error ocurred on save. I've fixed this.

When trying to write a model with a kredis attribute to the cache using `Rails.cache.write`, a `_no_dump_data` error is raised.

```ruby
class User < ApplicationRecord
  kredis_hash :source_locations
end

user = User.last
user.source_locations["key"] = "value"
Rails.cache.write user.cache_key, user

/rails-c3664b0c2b50/activesupport/lib/active_support/cache.rb:979:in `dump': no _dump_data is defined for class Hiredis::Ext::Connection (TypeError)
```

Rails: https://github.com/rails/rails/commit/c3664b0c2b509fc0a47929f42afbd716959c8f4c
Kredis: 90176e63609414171b6fff3c1e3919c7f710d138
Redis: 4.4.0
Hiredis: 0.6.3

cc @julianrubisch

**Comment by brenogazzola** [comment]
1. Yes
2. Yes
3. No

Step by step was:
1. Add `kredis_hash` to the model
2. Open the console
3. Grab a user from database
4. Set a value in the hash
5. Save
6. Error is raised

If I replace `kredis_hash` with `kredis_flag` and do `mark` then `save!` I don't get any error.

**Comment by brenogazzola** [comment]
My bad. Went back to check my code, and there is `Rails.cache`:

```
after_commit :expire_cache

def expire_cache
  Rails.cache.write self.class.cache_key(id), self
end
```

**Comment by brenogazzola** [comment]
And it seems I rushed too much to report this bug. I tried `kredis_flag` now and got the same error. It seems this is a more general Kredis error, not something from your `hash` code, sorry.

**Comment by julianrubisch** [comment]
FWIW I once had a similar error and it turns out you can exclude instance variables from marshaling: https://stackoverflow.com/questions/32876672/how-to-exclude-an-instance-variable-from-marshal-dump/32877159#32877159
