### ISSUE TITLE
Sets should not sort by default

### ISSUE THREAD

**Issue by MrHubble** [rails/kredis#42]
**Behaviour**

The [redis docs state](https://redis.io/topics/data-types) that _"Redis Sets are an unordered collection of Strings."_. However, with kredis, it appears that we are sorting sets:

https://github.com/rails/kredis/blob/3b8bec3b225370e1588fd43eef6a437c0cf7baa6/lib/kredis/types/set.rb#L6-L8

```rb
set = Kredis.set "myset"
set.add [55, 22, 33]
set.members 
 => [22, 33, 55]
```

**Expected behaviour**

```rb
set = Kredis.set "myset"
set.add [55, 22, 33]
set.members 
 => [55, 22, 33]
```

**Comment by dhh** [comment]
Kredis isn't trying to map 1-1 with Redis types. The intention is to use Redis as a backend for Ruby data types. But I think it's fair that we should document where someone might be inclined to expect the same behavior from Redis. If you want to do a PR for that here, please do 🙏

**Comment by MrHubble** [comment]
Thanks for taking the time to respond David. I figured out that when I correctly used `append` rather than `prepend`, a unique list covered my use case.
