### ISSUE TITLE
Allow to touch an ActiveRecord when a kredis attribute updates

### ISSUE THREAD

**Issue by julianrubisch** [rails/kredis#50]
In one of my applications, I have to construct very intricate cache keys which include all of the possible combinations of kredis attributes:

`cache [@topic, @topic.expanded_sections]` etc. 

I reckoned that in some situatons it would be nice to say

`kredis_set @topic.expanded_sections, touch: true` to allow touching of the record, thus eliminating a lot of cache keys. I think this should be doable with minimum effort. WDYT?

**Comment by julianrubisch** [comment]
of course, it's perfectly doable with a callback, just the logic can get a bit jumbled up because there's only one callback you can specify per attribute.

```rb
class Post < ApplicationRecord
  kredis_set :active_users, callback :notify_and_touch

  def notify_and_touch
    active_users.members.map ...
    touch
  end
end

class Project < ApplicationRecord
  kredis_hash :expanded_fields, callback :update_and_touch

  def update_and_touch
    expanded_fields.to_h.map ...
    touch
  end
end
```

Adding a `touch: true` option would make this sort of an aspect you don't have to think about too much. But I see your point, too, because `Kredis::Attributes` can of course be included in non-AR models, too.

**Comment by dhh** [comment]
Yeah, that's what I'm thinking. Making Kredis know about AR internals seems like a step too far.
