### ISSUE TITLE
Kredis methods are undefined in production for non-ActiveRecord models

### ISSUE THREAD

**Issue by EmCousin** [rails/kredis#60]
Hi,

First, thank you for this great gem.

I'm encountering an error when trying to use Kredis methods like `kredis_string`,  `kredis_json`, etc. in a class that inherits from a base class that includes `ActiveModel::Model`. This issue does not occur in development, only in production, preventing the app to boot.

The error : 
```
undefined method `kredis_json' for Foo::Bar:Class (NoMethodError)
```

How to reproduce the error:
```ruby
# Gemfile.rb
gem 'kredis' ## => bundle install

# app/models/foo/base.rb
module Foo
  class Base
    include ActiveModel::Model
  end
end

# app/models/foo/bar.rb
module Foo
  class Bar < Base
    kredis_json :metadata # causes the app to 💥 when booting
  end
end
```

I wonder it this might have something to do with the way `Kredis::Attributes` gets included in `ActiveModel::Model` [here](https://github.com/rails/kredis/blob/main/lib/kredis/railtie.rb#L26). Could it be due to the fact it is called in `config.after_initialize` callback instead of a load hook like it's done with ActiveRecord?

Just trying to wrap my head around this. The current workaround I use is to include explicitly `Kredis::Attributes`:

```ruby
module Foo
  class Bar < Base
    include Kredis::Attributes

    kredis_json :metadata # it works ✅ 
  end
end
```

Is it how we should actually use it?

### Background
- Rails 7
- Kredis 1.0.1

**Comment by dhh** [comment]
@fxn Would you know what's up here?

**Comment by fxn** [comment]
Yo!

Yes, @EmCousin guess is correct. Eager loading happens in the finisher [here](https://github.com/rails/rails/blob/15a2ff1d5bc9dcc3b120c31180c4c6a3d7d79ff3/railties/lib/rails/application/finisher.rb#L75), and the `after_initialize` hook runs [later](https://github.com/rails/rails/blob/15a2ff1d5bc9dcc3b120c31180c4c6a3d7d79ff3/railties/lib/rails/application/finisher.rb#L85).

This relative order [was the same in Rails 5](https://github.com/rails/rails/blob/v5.2.0/railties/lib/rails/application/finisher.rb#L66-L76).

I'd suspect that if you ran development mode with eager loading enabled, you'll be able to reproduce and test a solution locally.

I believe the idiomatic thing to do would be to define a load hook for Active Model. But that would need a release of Rails. Meanwhile, `activemodel` is a dependency of `activerecord` and its loading happens [early on](https://github.com/rails/rails/blob/15a2ff1d5bc9dcc3b120c31180c4c6a3d7d79ff3/activerecord/lib/active_record.rb#L28). I believe the `include` in Kredis could happen within the `on_load` hook of Active Record, as a temporary workaround.

@EmCousin while a solution for Kredis is worked out, in your application you can do the same. Throw this in and initializer or `config/application.rb`:

```ruby
# See https://github.com/rails/kredis/issues/60.
ActiveSupport.on_load(:active_record) do
  ActiveModel::Model.include Kredis::Attributes if defined?(ActiveModel::Model)
end
```

I have not tested this, but module inclusion is idempotent, so this won't interfere with Kredis doing the same later. That way, you can leave your application code clean and just remove the trick when an update upstream makes it no longer necessary.

**Comment by EmCousin** [comment]
Thanks @fxn!

- [x] Activating `eager_load` does reproduce the issue in development environment
- [x] Your workaround works. I put it in an initializer named `config/initializers/kredis.rb` rather than straight to `config/application.rb` though, since it listens to `ActiveSupport.on_load`

Looking forward to the update! 🙂

**Comment by fxn** [comment]
@EmCousin cool!

> I put it in an initializer named config/initializers/kredis.rb rather than straight to config/application.rb though, since it listens to ActiveSupport.on_load.

What do you mean?

**Comment by EmCousin** [comment]
I mean that this: 

```ruby
# See https://github.com/rails/kredis/issues/60.
ActiveSupport.on_load(:active_record) do
  ActiveModel::Model.include Kredis::Attributes
end
```

does not _have_ to be put straight into `config/application.rb` if you don't want to. You can put this piece of code in an initializer and it will work just as well

**Comment by fxn** [comment]
@EmCousin perfect :).
