### ISSUE TITLE
Default proc if empty

### ISSUE THREAD

**Issue by tleish** [rails/kredis#66]
Is there a way to set a default value for a list using a proc?  I'm thinking something like:

```ruby
class User < ApplicationRecord
  kredis_list :role_ids, default: ->(user) { user.roles.pluck(:id) }
end
```

Then if there's a nil value (either because it was never created or expired at some point), it recreates itself with the latest data.

I can accomplish the same thing with:

```ruby
class User < ApplicationRecord
  kredis_list :role_ids_cache, default: ->(user) { user.roles.pluck(:id) }

  def role_ids
    self.role_ids_cache.append(self.roles.pluck(:id)) unless self.role_ids_cache.elements.empty?
    self.role_ids_cache
  end
end
```

... but I prefer dealing with one method/variable vs two.

**Comment by dhh** [comment]
I like the idea of this. Please do explore as a PR 👍
