### ISSUE TITLE
Target Redis server version

### ISSUE THREAD

**Issue by lewispb** [rails/kredis#77]
While working on a feature recently I was exploring the use of the `ZADD` options `GT` and `LT`. These are [only available in Redis 6.2 onwards](https://redis.io/commands/ZADD#history).

Do we have a minimum Redis server version in mind while developing Kredis? If not, can we document one?

The only reference to a version I could see was this line: https://github.com/rails/kredis/blob/main/lib/kredis/migration.rb#L8

**Comment by dhh** [comment]
I believe we're at Redis 4+ at the moment since that's what Rails suggest in the default Gemfile.

But we probably could just gate new features on a redis version check? Then fail if not available?

**Comment by lewispb** [comment]
Added a note to the readme in https://github.com/rails/kredis/pull/79.

I backed away from `GT` / `LT` so nothing in mind that would require gating right now, but good to know that's an option for the future.

Might be worth also adding a matrix of supported Redis server versions, say 4 and 6.2, and client libraries to CI?
