### ISSUE TITLE
Error of syntax

### ISSUE THREAD

**Issue by JohnAnon9771** [rails/kredis#99]
Hello, when I try to run `./bin/rails kredis:install` I get a syntax error `expecting ')'` in `types/proxy.rb:9`

I use `rails 6.0.5` and `redis 4.5.1`

![image](https://user-images.githubusercontent.com/42195321/192048132-61c693aa-2ffe-4e3d-aac9-05dfdf9c014d.png)

Can someone help me?

**Comment by marcoroth** [comment]
Hey @JohnAnon9771, seems like you are on a rather old version of Kredis (`0.2.0` was released over a year ago). 

You might have more success using the most recent version?

**Comment by skipkayhil** [comment]
> You might have more success using the most recent version?

To add to this, you're probably not going to be able to update the version without first updating Ruby. I'm guessing you are on Ruby 2.6.x, and Kredis 0.2.0 incorrectly had >= 2.6.0 as a version requirement. Newer versions correctly require Ruby 2.7, which is the version that supports the `(...)` syntax

**Comment by JohnAnon9771** [comment]
@marcoroth Thank you very much for the reply, I hadn't noticed the version. Now the problem is with my version of ruby, I currently use `2.6.10` and kredis needs `2.7`

**Comment by JohnAnon9771** [comment]
> > You might have more success using the most recent version?
> 
> To add to this, you're probably not going to be able to update the version without first updating Ruby. I'm guessing you are on Ruby 2.6.x, and Kredis 0.2.0 incorrectly had >= 2.6.0 as a version requirement. Newer versions correctly require Ruby 2.7, which is the version that supports the `(...)` syntax

Yes you are right, I use `2.6.10`

**Comment by JohnAnon9771** [comment]
I think it would be interesting if it had the ruby requirement in the readme.
